---
application-auto-scaling_DeregisterScalableTarget:
  title: Use Remove-AASScalableTarget
  title_abbrev: Remove-AASScalableTarget
  synopsis: use Remove-AASScalableTarget
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Remove-AASScalableTarget
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This cmdlet deregisters an Application Auto Scaling scalable target.Deregistering a scalable target deletes the scaling policies that are associated with it.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/application-autoscaling_Remove-AASScalableTarget.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">Confirm
            Are you sure you want to perform this action?
            Performing the operation "Remove-AASScalableTarget (DeregisterScalableTarget)" on target "fleet/MyFleet".
            [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y</programlisting>
  services:
    application-auto-scaling:
      DeregisterScalableTarget:

