---
application-auto-scaling_DeleteScheduledAction:
  title: Use Remove-AASScheduledAction
  title_abbrev: Remove-AASScheduledAction
  synopsis: use Remove-AASScheduledAction
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Remove-AASScheduledAction
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This cmdlet deletes the specified scheduled action for an Application Auto Scaling scalable target.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/application-autoscaling_Remove-AASScheduledAction.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">Confirm
            Are you sure you want to perform this action?
            Performing the operation "Remove-AASScheduledAction (DeleteScheduledAction)" on target "WeekDaysFleetScaling".
            [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y</programlisting>
  services:
    application-auto-scaling:
      DeleteScheduledAction:

