---
appstream_UpdateDirectoryConfig:
  title: Use Update-APSDirectoryConfig
  title_abbrev: Update-APSDirectoryConfig
  synopsis: use Update-APSDirectoryConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This sample updates the Directory configuration created in AppStream</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/appstream_Update-APSDirectoryConfig.1.1.ps1
          description: 
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">CreatedTime           DirectoryName OrganizationalUnitDistinguishedNames           ServiceAccountCredentials
            -----------           ------------- ------------------------------------           -------------------------
            12/27/2019 3:50:02 PM contoso.com   {OU=AppStreamNew,OU=Contoso,DC=Contoso,DC=com} Amazon.AppStream.Model.ServiceAccountCredentials</programlisting>
  services:
    appstream:
      UpdateDirectoryConfig: 

