---
appstream_CreateDirectoryConfig:
  title: Use New-APSDirectoryConfig
  title_abbrev: New-APSDirectoryConfig
  synopsis: use New-APSDirectoryConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This sample creates a directory configuration in AppStream</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/appstream_New-APSDirectoryConfig.1.1.ps1
          description: 
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">CreatedTime            DirectoryName OrganizationalUnitDistinguishedNames        ServiceAccountCredentials
            -----------            ------------- ------------------------------------        -------------------------
            12/27/2019 11:00:30 AM contoso.com   {OU=AppStream,OU=Contoso,DC=Contoso,DC=com} Amazon.AppStream.Model.ServiceAccountCredentials</programlisting>
  services:
    appstream:
      CreateDirectoryConfig: 

