---
auto-scaling_DeleteNotificationConfiguration:
  title: Use Remove-ASNotificationConfiguration
  title_abbrev: Remove-ASNotificationConfiguration
  synopsis: use Remove-ASNotificationConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Remove-ASNotificationConfiguration
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example deletes the specified notification action. You are prompted for confirmation before the operation proceeds.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Remove-ASNotificationConfiguration.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">Confirm
            Are you sure you want to perform this action?
            Performing operation "Remove-ASNotificationConfiguration (DeleteNotificationConfiguration)" on Target
            "arn:aws:sns:us-west-2:123456789012:my-topic".
            [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):</programlisting>
          snippet_files: []
        - description: '<emphasis role="bold">Example 2: If you specify the Force parameter, you are not prompted for confirmation before the operation proceeds.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Remove-ASNotificationConfiguration.2.1.ps1
  services:
    auto-scaling:
      DeleteNotificationConfiguration:


