---
auto-scaling_DescribeNotificationConfigurations:
  title: Use Get-ASNotificationConfiguration
  title_abbrev: Get-ASNotificationConfiguration
  synopsis: use Get-ASNotificationConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-ASNotificationConfiguration
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This example describes the notification actions associated with the specified Auto Scaling group.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Get-ASNotificationConfiguration.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">AutoScalingGroupName : my-asg
            NotificationType     : auto-scaling:EC2_INSTANCE_LAUNCH
            TopicARN             : arn:aws:sns:us-west-2:123456789012:my-topic

            AutoScalingGroupName : my-asg
            NotificationType     : auto-scaling:EC2_INSTANCE_TERMINATE
            TopicARN             : arn:aws:sns:us-west-2:123456789012:my-topic</programlisting>
        - snippet_files: []
          description: '<emphasis role="bold">Example 2: This example describes the notification actions associated with all your Auto Scaling groups.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/auto-scaling_Get-ASNotificationConfiguration.2.1.ps1
          description:
  services:
    auto-scaling:
      DescribeNotificationConfigurations:


