---
cloud9_DescribeEnvironmentStatus:
  title: Use Get-C9EnvironmentStatus
  title_abbrev: Get-C9EnvironmentStatus
  synopsis: use Get-C9EnvironmentStatus
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-C9EnvironmentStatus
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets status information for the specified &AWS; Cloud9 development environment.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/cloud9_Get-C9EnvironmentStatus.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">Message                     Status
            -------                     ------
            Environment is ready to use ready</programlisting>
          snippet_files: []
  services:
    cloud9:
      DescribeEnvironmentStatus:

