---
cloudfront_GetCloudFrontOriginAccessIdentityConfig:
  title: Use Get-CFCloudFrontOriginAccessIdentityConfig
  title_abbrev: Get-CFCloudFrontOriginAccessIdentityConfig
  synopsis: use Get-CFCloudFrontOriginAccessIdentityConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example returns configuration information about a single Amazon CloudFront origin access identity, specified by the -Id parameter. Errors occur if no -Id parameter is specified..</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/cloudfront_Get-CFCloudFrontOriginAccessIdentityConfig.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">      CallerReference                                             Comment
                  ---------------                                             -------
                  mycallerreference: 2/1/2011 1:16:32 PM                      Caller reference: 2/1/2011 1:16:32 PM</programlisting>
          snippet_files: []
  services:
    cloudfront:
      GetCloudFrontOriginAccessIdentityConfig: 

