---
codedeploy_ListDeploymentGroups:
  title: Use Get-CDDeploymentGroupList
  title_abbrev: Get-CDDeploymentGroupList
  synopsis: use Get-CDDeploymentGroupList
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets a list of deployment groups for the specified application.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentGroupList.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ApplicationName              DeploymentGroups                                    NextToken
            ---------------              ----------------                                    ---------
            CodeDeployDemoApplication    {CodeDeployDemoFleet, CodeDeployProductionFleet}</programlisting>
          snippet_files: []
  services:
    codedeploy:
      ListDeploymentGroups: 

