---
codedeploy_RegisterApplicationRevision:
  title: Use Register-CDApplicationRevision
  title_abbrev: Register-CDApplicationRevision
  synopsis: use Register-CDApplicationRevision
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example registers an application revision with the specified Amazon S3 location, for the specified application.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Register-CDApplicationRevision.1.1.ps1
  services:
    codedeploy:
      RegisterApplicationRevision: 

