---
codedeploy_DeleteApplication:
  title: Use Remove-CDApplication
  title_abbrev: Remove-CDApplication
  synopsis: use Remove-CDApplication
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example deletes the application with the specified name. The command will prompt for confirmation before proceeding. Add the -Force parameter to delete the application without a prompt.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Remove-CDApplication.1.1.ps1
  services:
    codedeploy:
      DeleteApplication: 

