---
codedeploy_GetDeploymentGroup:
  title: Use Get-CDDeploymentGroup
  title_abbrev: Get-CDDeploymentGroup
  synopsis: use Get-CDDeploymentGroup
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-CDDeploymentGroup
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets information about the specified deployment group.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentGroup.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ApplicationName              : CodeDeployDemoApplication
            AutoScalingGroups            : {}
            DeploymentConfigName         : CodeDeployDefault.OneAtATime
            DeploymentGroupId            : 7d7c098a-b444-4b27-96ef-22791EXAMPLE
            DeploymentGroupName          : CodeDeployDemoFleet
            Ec2TagFilters                : {Name}
            OnPremisesInstanceTagFilters : {}
            ServiceRoleArn               : arn:aws:iam::80398EXAMPLE:role/CodeDeploySampleStack-4ph6EX-CodeDeployTrustRole-O9MWP7XTL8EX
            TargetRevision               : Amazon.CodeDeploy.Model.RevisionLocation</programlisting>
          snippet_files: []
  services:
    codedeploy:
      GetDeploymentGroup:

