---
codedeploy_BatchGetDeployments:
  title: Use Get-CDDeploymentBatch
  title_abbrev: Get-CDDeploymentBatch
  synopsis: use Get-CDDeploymentBatch
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets information about the specified deployments.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentBatch.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ApplicationName               : CodeDeployDemoApplication
            CompleteTime                  : 7/23/2015 11:26:04 PM
            CreateTime                    : 7/23/2015 11:24:43 PM
            Creator                       : user
            DeploymentConfigName          : CodeDeployDefault.OneAtATime
            DeploymentGroupName           : CodeDeployDemoFleet
            DeploymentId                  : d-QZMRGSTEX
            DeploymentOverview            : Amazon.CodeDeploy.Model.DeploymentOverview
            Description                   :
            ErrorInformation              :
            IgnoreApplicationStopFailures : False
            Revision                      : Amazon.CodeDeploy.Model.RevisionLocation
            StartTime                     : 1/1/0001 12:00:00 AM
            Status                        : Succeeded

            ApplicationName               : CodePipelineDemoApplication
            CompleteTime                  : 7/23/2015 6:07:30 PM
            CreateTime                    : 7/23/2015 6:06:29 PM
            Creator                       : user
            DeploymentConfigName          : CodeDeployDefault.OneAtATime
            DeploymentGroupName           : CodePipelineDemoFleet
            DeploymentId                  : d-RR0T5KTEX
            DeploymentOverview            : Amazon.CodeDeploy.Model.DeploymentOverview
            Description                   :
            ErrorInformation              :
            IgnoreApplicationStopFailures : False
            Revision                      : Amazon.CodeDeploy.Model.RevisionLocation
            StartTime                     : 1/1/0001 12:00:00 AM
            Status                        : Succeeded</programlisting>
          snippet_files: []
  services:
    codedeploy:
      BatchGetDeployments: 

