---
codedeploy_GetApplication:
  title: Use Get-CDApplication
  title_abbrev: Get-CDApplication
  synopsis: use Get-CDApplication
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-CDApplication
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets information about the specified application.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDApplication.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ApplicationId                           ApplicationName              CreateTime              LinkedToGitHub
            -------------                           ---------------              ----------              --------------
            e07fb938-091e-4f2f-8963-4d3e8EXAMPLE    CodeDeployDemoApplication    7/20/2015 9:49:48 PM    False</programlisting>
          snippet_files: []
  services:
    codedeploy:
      GetApplication:

