---
codedeploy_ListDeploymentConfigs:
  title: Use Get-CDDeploymentConfigList
  title_abbrev: Get-CDDeploymentConfigList
  synopsis: use Get-CDDeploymentConfigList
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-CDDeploymentConfigList
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example gets a list of available deployment configurations.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/codedeploy_Get-CDDeploymentConfigList.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ThreeQuartersHealthy
            CodeDeployDefault.OneAtATime
            CodeDeployDefault.AllAtOnce
            CodeDeployDefault.HalfAtATime</programlisting>
          snippet_files: []
  services:
    codedeploy:
      ListDeploymentConfigs:

