---
config-service_DescribeAggregationAuthorizations:
  title: Use Get-CFGAggregationAuthorizationList
  title_abbrev: Get-CFGAggregationAuthorizationList
  synopsis: use Get-CFGAggregationAuthorizationList
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example retrieves authorizations granted to aggregators.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGAggregationAuthorizationList.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">AggregationAuthorizationArn                                                            AuthorizedAccountId AuthorizedAwsRegion CreationTime
            ---------------------------                                                            ------------------- ------------------- ------------
            arn:aws:config-service:eu-west-1:123456789012:aggregation-authorization/123456789012/eu-west-1 123456789012        eu-west-1           8/26/2019 12:55:27 AM</programlisting>
          snippet_files: []
  services:
    config-service:
      DescribeAggregationAuthorizations: 


