---
config-service_GetComplianceSummaryByConfigRule:
  title: Use Get-CFGComplianceSummaryByConfigRule
  title_abbrev: Get-CFGComplianceSummaryByConfigRule
  synopsis: use Get-CFGComplianceSummaryByConfigRule
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-CFGComplianceSummaryByConfigRule
        excerpts:
        - description: '<emphasis role="bold">Example 1: This sample returns the number of Config rules that are non-compliant.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGComplianceSummaryByConfigRule.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">CapExceeded CappedCount
            ----------- -----------
            False       9</programlisting>
          snippet_files: []
  services:
    config-service:
      GetComplianceSummaryByConfigRule:


