---
config-service_DescribeConfigRuleEvaluationStatus:
  title: Use Get-CFGConfigRuleEvaluationStatus
  title_abbrev: Get-CFGConfigRuleEvaluationStatus
  synopsis: use Get-CFGConfigRuleEvaluationStatus
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This sample returns the status information for the given config rules. </emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGConfigRuleEvaluationStatus.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ConfigRuleArn                : arn:aws:config:eu-west-1:123456789012:config-rule/config-rule-kvq1wk
            ConfigRuleId                 : config-rule-kvq1wk
            ConfigRuleName               : root-account-mfa-enabled
            FirstActivatedTime           : 8/27/2019 8:05:17 AM
            FirstEvaluationStarted       : True
            LastErrorCode                :
            LastErrorMessage             :
            LastFailedEvaluationTime     : 1/1/0001 12:00:00 AM
            LastFailedInvocationTime     : 1/1/0001 12:00:00 AM
            LastSuccessfulEvaluationTime : 12/13/2019 8:12:03 AM
            LastSuccessfulInvocationTime : 12/13/2019 8:12:03 AM

            ConfigRuleArn                : arn:aws:config:eu-west-1:123456789012:config-rule/config-rule-z1s23b
            ConfigRuleId                 : config-rule-z1s23b
            ConfigRuleName               : vpc-flow-logs-enabled
            FirstActivatedTime           : 8/14/2019 6:23:44 AM
            FirstEvaluationStarted       : True
            LastErrorCode                :
            LastErrorMessage             :
            LastFailedEvaluationTime     : 1/1/0001 12:00:00 AM
            LastFailedInvocationTime     : 1/1/0001 12:00:00 AM
            LastSuccessfulEvaluationTime : 12/13/2019 7:12:01 AM
            LastSuccessfulInvocationTime : 12/13/2019 7:12:01 AM</programlisting>
          snippet_files: []
  services:
    config-service:
      DescribeConfigRuleEvaluationStatus: 


