---
config-service_PutDeliveryChannel:
  title: Use Write-CFGDeliveryChannel
  title_abbrev: Write-CFGDeliveryChannel
  synopsis: use Write-CFGDeliveryChannel
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Write-CFGDeliveryChannel
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example changes the deliveryFrequency property of an existing delivery channel.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/config-service_Write-CFGDeliveryChannel.1.1.ps1
  services:
    config-service:
      PutDeliveryChannel:


