---
config-service_GetAggregateComplianceDetailsByConfigRule:
  title: Use Get-CFGAggregateComplianceDetailsByConfigRule
  title_abbrev: Get-CFGAggregateComplianceDetailsByConfigRule
  synopsis: use Get-CFGAggregateComplianceDetailsByConfigRule
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: "<emphasis role=\"bold\">Example 1: This example returns the evaluation results selecting the output with resource-id and resource-type for the &AWS; Config rule 'desired-instance-type' which are in 'COMPLIANT' state for the given account, aggregator, region and config rule</emphasis>"
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGAggregateComplianceDetailsByConfigRule.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ConfigRuleName        ResourceId          ResourceType
            --------------        ----------          ------------
            desired-instance-type i-0f1bf2f34c5678d12 AWS::EC2::Instance
            desired-instance-type i-0fd12dd3456789123 AWS::EC2::Instance</programlisting>
          snippet_files: []
  services:
    config-service:
      GetAggregateComplianceDetailsByConfigRule: 


