---
config-service_DescribeComplianceByConfigRule:
  title: Use Get-CFGComplianceByConfigRule
  title_abbrev: Get-CFGComplianceByConfigRule
  synopsis: use Get-CFGComplianceByConfigRule
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example retrieves compliances details for the rule ebs-optimized-instance, for which there is no current evaluation results for the rule, hence it returns INSUFFICIENT_DATA</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGComplianceByConfigRule.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ComplianceContributorCount ComplianceType
            -------------------------- --------------
                                       INSUFFICIENT_DATA</programlisting>
          snippet_files: []
        - description: '<emphasis role="bold">Example 2: This example returns the number of non-compliant resources for the rule ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGComplianceByConfigRule.2.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">CapExceeded CappedCount
            ----------- -----------
            False       2</programlisting>
          snippet_files: []
  services:
    config-service:
      DescribeComplianceByConfigRule: 


