---
config-service_GetComplianceDetailsByConfigRule:
  title: Use Get-CFGComplianceDetailsByConfigRule
  title_abbrev: Get-CFGComplianceDetailsByConfigRule
  synopsis: use Get-CFGComplianceDetailsByConfigRule
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example obtains the evaluation results for the rule access-keys-rotated and returns the output grouped by compliance-type</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGComplianceDetailsByConfigRule.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">Count Name                      Group
            ----- ----                      -----
                2 COMPLIANT                 {Amazon.ConfigService.Model.EvaluationResult, Amazon.ConfigService.Model.EvaluationResult}
                5 NON_COMPLIANT             {Amazon.ConfigService.Model.EvaluationResult, Amazon.ConfigService.Model.EvaluationResult, Amazon.ConfigService.Model.EvaluationRes...</programlisting>
          snippet_files: []
        - description: '<emphasis role="bold">Example 2: This example queries compliance details for the rule access-keys-rotated for COMPLIANT resources.</emphasis>'
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/config-service_Get-CFGComplianceDetailsByConfigRule.2.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: |-
            <programlisting language="none" role="nocopy">ConfigRuleName      ResourceId            ResourceType
            --------------      ----------            ------------
            access-keys-rotated BCAB1CDJ2LITAPVEW3JAH AWS::IAM::User
            access-keys-rotated BCAB1CDJ2LITL3EHREM4Q AWS::IAM::User</programlisting>
          snippet_files: []
  services:
    config-service:
      GetComplianceDetailsByConfigRule: 


