---
ec2_RevokeSecurityGroupIngress:
  title: Use Revoke-EC2SecurityGroupIngress
  title_abbrev: Revoke-EC2SecurityGroupIngress
  synopsis: use Revoke-EC2SecurityGroupIngress
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Revoke-EC2SecurityGroupIngress
        excerpts:
        - description: '<emphasis role="bold">Example 1: This example revokes access to TCP port 22 from the specified address range for the specified security group for EC2-VPC. Note that you must identify security groups for EC2-VPC using the security group ID not the security group name. The syntax used by this example requires PowerShell version 3 or higher.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/ec2_Revoke-EC2SecurityGroupIngress.1.1.ps1
        - description: <emphasis role="bold">Output:</emphasis>
          snippet_files: []
        - description: <programlisting language="none" role="nocopy">Revoke-EC2SecurityGroupIngress -GroupId sg-12345678 -IpPermission $ip</programlisting>
          snippet_files: []
        - description: '<emphasis role="bold">Example 2: With PowerShell version 2, you must use New-Object to create the IpPermission object.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/ec2_Revoke-EC2SecurityGroupIngress.2.1.ps1
        - description: '<emphasis role="bold">Example 3: This example revokes access to TCP port 22 from the specified address range for the specified security group for EC2-Classic. The syntax used by this example requires PowerShell version 3 or higher.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/ec2_Revoke-EC2SecurityGroupIngress.3.1.ps1
        - description: '<emphasis role="bold">Example 4: With PowerShell version 2, you must use New-Object to create the IpPermission object.</emphasis>'
          snippet_files: []
        - description:
          snippet_files:
          - .doc_gen/snippet_files/ec2_Revoke-EC2SecurityGroupIngress.4.1.ps1
  services:
    ec2:
      RevokeSecurityGroupIngress:

