---
ec2_UpdateSecurityGroupRuleDescriptionsIngress:
  title: Use Update-EC2SecurityGroupRuleIngressDescription
  title_abbrev: Update-EC2SecurityGroupRuleIngressDescription
  synopsis: use Update-EC2SecurityGroupRuleIngressDescription
  languages:
    PowerShell:
      versions:
      - sdk_version: 5
        sdk_action: Update-EC2SecurityGroupRuleIngressDescription
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: Updates the description of an existing ingress (inbound) security group rule.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/ec2_Update-EC2SecurityGroupRuleIngressDescription.1.1.ps1
          description:
        - snippet_files: []
          description: '<emphasis role="bold">Example 2: Removes the description of an existing ingress (inbound) security group rule (by omitting the parameter in the request).</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/ec2_Update-EC2SecurityGroupRuleIngressDescription.2.1.ps1
          description:
  services:
    ec2:
      UpdateSecurityGroupRuleDescriptionsIngress:

