---
route-53_DeleteQueryLoggingConfig:
  title: Use Remove-R53QueryLoggingConfig
  title_abbrev: Remove-R53QueryLoggingConfig
  synopsis: use Remove-R53QueryLoggingConfig
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Remove-R53QueryLoggingConfig
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This example removes the specified configuration for DNS query logging.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/route-53_Remove-R53QueryLoggingConfig.1.1.ps1
          description:
  services:
    route-53:
      DeleteQueryLoggingConfig:


