---
s3_ListBucketInventoryConfigurations:
  title: Use Get-S3BucketInventoryConfigurationList
  title_abbrev: Get-S3BucketInventoryConfigurationList
  synopsis: use Get-S3BucketInventoryConfigurationList
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This command returns the first 100 inventory configurations of the given S3 bucket.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketInventoryConfigurationList.1.1.ps1
          description: 
  services:
    s3:
      ListBucketInventoryConfigurations: 

