---
s3_GetBucketAnalyticsConfiguration:
  title: Use Get-S3BucketAnalyticsConfiguration
  title_abbrev: Get-S3BucketAnalyticsConfiguration
  synopsis: use Get-S3BucketAnalyticsConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-S3BucketAnalyticsConfiguration
        excerpts:
        - snippet_files: []
          description: "<emphasis role=\"bold\">Example 1: This command returns the details of the analytics filter with the name 'testfilter' in the given S3 bucket.</emphasis>"
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketAnalyticsConfiguration.1.1.ps1
          description:
  services:
    s3:
      GetBucketAnalyticsConfiguration:

