---
s3_GetBucketAccelerateConfiguration:
  title: Use Get-S3BucketAccelerateConfiguration
  title_abbrev: Get-S3BucketAccelerateConfiguration
  synopsis: use Get-S3BucketAccelerateConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-S3BucketAccelerateConfiguration
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This command returns the value Enabled, if the transfer acceleration settings is enabled for the bucket specified.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketAccelerateConfiguration.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: "<programlisting language=\"none\" role=\"nocopy\">Value                                  \n-----                                    \nEnabled</programlisting>"
  services:
    s3:
      GetBucketAccelerateConfiguration:

