---
s3_GetBucketInventoryConfiguration:
  title: Use Get-S3BucketInventoryConfiguration
  title_abbrev: Get-S3BucketInventoryConfiguration
  synopsis: use Get-S3BucketInventoryConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - snippet_files: []
          description: "<emphasis role=\"bold\">Example 1: This command returns the details of the inventory named 'testinventory' for the given S3 bucket.</emphasis>"
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3BucketInventoryConfiguration.1.1.ps1
          description: 
  services:
    s3:
      GetBucketInventoryConfiguration: 

