---
s3_GetLifecycleConfiguration:
  title: Use Get-S3LifecycleConfiguration
  title_abbrev: Get-S3LifecycleConfiguration
  synopsis: use Get-S3LifecycleConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        sdk_action: Get-S3LifecycleConfiguration
        excerpts:
        - snippet_files: []
          description: '<emphasis role="bold">Example 1: This example retrieves lifecycle configuration for the bucket.</emphasis>'
        - snippet_files:
          - .doc_gen/snippet_files/s3_Get-S3LifecycleConfiguration.1.1.ps1
          description:
        - snippet_files: []
          description: <emphasis role="bold">Output:</emphasis>
        - snippet_files: []
          description: |-
            <programlisting language="none" role="nocopy">Rules
            -----
            {Remove-in-150-days, Archive-to-Glacier-in-30-days}</programlisting>
  services:
    s3:
      GetLifecycleConfiguration:

