---
s3_DeleteBucketMetricsConfiguration:
  title: Use Remove-S3BucketMetricsConfiguration
  title_abbrev: Remove-S3BucketMetricsConfiguration
  synopsis: use Remove-S3BucketMetricsConfiguration
  languages:
    PowerShell:
      versions:
      - sdk_version: 4
        excerpts:
        - description: "<emphasis role=\"bold\">Example 1: The command removes the metrics filter with name 'testmetrics' in the given S3 bucket.</emphasis>"
          snippet_files: []
        - description: 
          snippet_files:
          - .doc_gen/snippet_files/s3_Remove-S3BucketMetricsConfiguration.1.1.ps1
  services:
    s3:
      DeleteBucketMetricsConfiguration: 

